name: CI Checks

on:
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      # step 1: clone the repo so it can be seen 
      - name: Check out code
        uses: actions/checkout@v4

      # step 2: setup the go toolchain 
      - name: Set up Go 1.25.0
        uses: actions/setup-go@v5
        with:
        go-version: '1.25'

      # step 3: install dependencies
      - name: Install dependencies
        run: go mod download

      # step 4: run tests
      - name: Tests
        run: go test -v ./...

      # step 5: If the tests are successful, build
      - name: Build
        run: go build -v ./...
  

 
